#!/bin/sh

set -e

### BEGIN INIT INFO
# Provides:          docker-compose service
# Required-Start:    $syslog $remote_fs docker
# Required-Stop:     $syslog $remote_fs docker
# Should-Start:      cgroupfs-mount cgroup-lite
# Should-Stop:       cgroupfs-mount cgroup-lite
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts docker-compose
# Description:       Start docker-compose
### END INIT INFO
NAME="compose-service"
DESCRIPTION="Docker compose service"
SCRIPTNAME=/etc/init.d/$NAME
UMBREL_ROOT=/home/umbrel

case "$1" in
  	start)
        if [ -f $UMBREL_ROOT/docker-compose.yml ]; then
		    cd $UMBREL_ROOT
			echo "Starting karen"
			./karen &
			echo "Starting Umbrel Docker services"
		    docker-compose up --build -d
            exit 0
        else
            echo "Cannot start umbrelbox service. No docker-compose.yml found in $UMBREL_ROOT"
            exit 1
        fi
		;;
	stop)
        if [ -f $UMBREL_ROOT/docker-compose.yml ]; then
		    echo "Stopping Umbrel Docker services"
		    cd $UMBREL_ROOT
		    docker-compose down
            exit 0
        else
            echo "Cannot stop umbrelbox service. No docker-compose.yml found in $UMBREL_ROOT"
            exit 1
        fi
		;;
	status)
		echo "Status"
		docker ps -a
        exit 0
		;;
	*)
		echo "Either 'start', 'stop', or 'status'"
		exit 1
        ;;
esac

exit 0
