#!/bin/sh

set -e

### BEGIN INIT INFO
# Provides:          docker-compose service
# Required-Start:    $syslog $remote_fs docker
# Required-Stop:     $syslog $remote_fs docker
# Should-Start:      cgroupfs-mount cgroup-lite
# Should-Stop:       cgroupfs-mount cgroup-lite
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts docker-compose
# Description:       Start docker-compose
### END INIT INFO
NAME="compose-service"
DESCRIPTION="Docker compose service"
SCRIPTNAME=/etc/init.d/$NAME
UMBREL_DIR=/home/umbrel

case "$1" in
        start)
        if [ -f $UMBREL_DIR/docker-compose.yml ]; then
                    cd $UMBREL_DIR
                    echo "Monitoring for OTA update signal file"
                    fswatch -o -v -0 --event Updated $UMBREL_DIR/update/START | xargs -0 -n 1 bash update.sh &
                    echo "Starting Umbrel containers"
                    docker-compose up -d
            exit 0
        else
            echo "Docker-compose file doesn't exist"
            exit 1
        fi
                ;;
        stop)
        if [ -f $UMBREL_DIR/docker-compose.yml ]; then
                    echo "Stopping docker"
                    cd $UMBREL_DIR
                    docker-compose down
            exit 0
        else
            echo "Docker-compose file doesn't exist"
            exit 1
        fi
		;;
	status)
		echo "Status"
		docker ps -a
        exit 0
		;;
	*)
		echo "Either 'start', 'stop', or 'status'"
		exit 1
        ;;
esac

exit 0