#!/bin/bash

set -e

### BEGIN INIT INFO
# Provides:          Umbrel service
# Required-Start:    $syslog $remote_fs docker
# Required-Stop:     $syslog $remote_fs docker
# Should-Start:      cgroupfs-mount cgroup-lite
# Should-Stop:       cgroupfs-mount cgroup-lite
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts Umbrel
# Description:       Start Umbrel
### END INIT INFO
NAME="umbrel"
DESCRIPTION="Umbrel service"
SCRIPTNAME=/etc/init.d/$NAME
UMBREL_ROOT=/home/umbrel/umbrel

case "$1" in
  	start)
        if [ -x $UMBREL_ROOT/scripts/start ]; then
			echo "Starting Umbrel..."
			echo
			if [ -f /etc/default/umbrel ]; then
				echo "Loading Umbrel OS environment variables..."
				source /etc/default/umbrel
			fi
		    cd $UMBREL_ROOT
			./scripts/start
            exit 0
        else
            echo "Cannot start umbrel service. No start script found in $UMBREL_ROOT"
            exit 1
        fi
		;;
	stop)
        if [ -x $UMBREL_ROOT/scripts/stop ]; then
		    echo "Stopping Umbrel..."
		    cd $UMBREL_ROOT
		    ./scripts/stop
            exit 0
        else
            echo "Cannot stop umbrel service. No stop script found in $UMBREL_ROOT"
            exit 1
        fi
		;;
	status)
		if [ -x $UMBREL_ROOT/scripts/status ]; then
		    echo "Getting Umbrel status..."
		    cd $UMBREL_ROOT
		    ./scripts/status
            exit 0
        else
            echo "Cannot get umbrel service's status. No status script found in $UMBREL_ROOT"
            exit 1
        fi
		;;
	*)
		echo "Either 'start', 'stop', or 'status'"
		exit 1
        ;;
esac

exit 0
