name: Build image on push or PR
on: ["push", "pull_request"]

jobs:
    build:

        runs-on: ubuntu-20.04
        
        steps:
        
        - uses: actions/checkout@v1

        - name: Run Apt-get update
          run: sudo apt-get update

        - name: Install dependencies
          run: sudo apt-get -y install quilt qemu-user-static debootstrap libarchive-tools

        - name: Nuke current Docker installation
          run: |
              sudo systemctl stop docker
              sudo apt-get purge docker-ce docker-ce-cli containerd.io moby-engine moby-cli
              sudo rm -rf /var/lib/docker
        
        - name: Re-install Docker
          run: |
              curl -fsSL https://get.docker.com -o get-docker.sh
              sudo sh get-docker.sh
              docker --version

        - name: Enable experimental features in Docker
          run: |
              sudo rm -rf /etc/docker/daemon.json
              echo '{"experimental": true}' | sudo tee -a /etc/docker/daemon.json
              sudo systemctl restart docker

        - name: Set image name
          run: |
              UMBREL_OS_VERSION="$(git describe --tags)"
              IMAGE_NAME="umbrel-os-${UMBREL_OS_VERSION}"
              echo "UMBREL_OS_VERSION=$UMBREL_OS_VERSION"  >> $GITHUB_ENV
              echo "IMAGE_NAME=$IMAGE_NAME"  >> $GITHUB_ENV

        - name: Run build script
          run: |
              echo "Building $IMAGE_NAME"
              sudo IMG_FILENAME=$IMAGE_NAME ZIP_FILENAME=$IMAGE_NAME UMBREL_OS_VERSION=$UMBREL_OS_VERSION ./build.sh

        - name: Copy ZIP to current working dir
          run: cp deploy/*.zip ./

        - name: Debug current working dir
          run: ls -la
        
        - name: Upload artifact
          uses: actions/upload-artifact@v2
          with:
            path: ${{ env.IMAGE_NAME }}.zip
            name: ${{ env.IMAGE_NAME }}.zip
